### PR TITLE
Added ligatures patch

### PR DESCRIPTION
**Pull request by mackarelfish**

### CODE REVIEW

**Comment by ertwro** [comment]
This breaks boxdraw.

**Comment by wundrweapon** [comment]
Thank you for this! I've been meaning to do it myself but never had the time

**Comment by alpha-tango-kilo** [comment]
`config.h` doesn't provide any settings like I can see in that linked post, so I'd wager they're probably not supported with the patch

**Comment by fakhriaunur** [comment]
> This give me error

I did #315 . No errors.

**Pull request merged**
