### PR TITLE
Install ST with pkgbuild

### PR DESCRIPTION
**Pull request by alrayyes**
Don't know if this is your style but i've modified the st repo so you can install it as an arch package. A cleaner way of doing it IMHO.

### CODE REVIEW

**Comment by LukeSmithxyz** [comment]
I'm going to close this request. This looks good for Arch users, but I want this repo to have maximum compatibility. If you want to commit a pkgbuild that doesn't break `make` compatibility, feel free to and open another pull request, but I don't want to cherrypick your commits myself.

**Comment by alrayyes** [comment]
No worries. Sadly that's the Achilles heel of st. If you want something
custom you really have to build it yourself.

You could however easily modify it to create a lukest package and push it
to aur. The package is basically identical to yours, the only difference is
that it doesn't include solarized light theme.

**Comment by LukeSmithxyz** [comment]
I might do that. I actually have never submitted something to the AUR, but this might be worth it seeing there are basically no builds of st there I think.

Do you know if I'd have to make any major changes to the pkgbuild you have for the upgrade to .8?

**Comment by alrayyes** [comment]
It already uses 0.8.1, which is the latest version. Actually a new  [solarized patch](https://st.suckless.org/patches/solarized/st-solarized-both-0.8.1.diff) has been released which should work with the latest version. All you have to do to install it is add it to the PKGBUILD and run ```updpkgsums``` to update the checksums. Everything *should* work out of the box then. So yeah, besides solarized you really don't need to change anything. Well, you'll probably want to change the fonts. Everything is in config.h.

It's all pretty straightforward, I use sed to cut out config stuff from the patches and then add the config stuff to config.h manually, everything is explained in [this tutorial](http://brianbuccola.com/how-to-build-and-install-st-suckless-simple-terminal-from-source-on-arch-linux/), which is what I used as a starting point.

There are 1 or 2 st builds in AUR, but of course they're opinionated. It should be pretty straightforward to create a package for Void as well.

**Pull request closed without merging**
