### PR TITLE
Keyboard select

### PR DESCRIPTION
**Pull request by ZakharEl**
+ modified suckless **keyboard select patch** rewritten to be **compatible with your version of st** under the branch of keyboard-select
+ let me know if you'd like **this branch merged with master**
+ **or kept as seperate branch**
+ if you do not wish to incorporate this pull request then I would appreciate it greatly if you'd let me know why: **don't want to incorporate the keyboard select feature periode, implementation of it isn't the best, documentation could be better, etc.**
+ appreciate the channel and this is my first pull request, so I appologize if I did it wrong in any way.

### CODE REVIEW

**Comment by ZakharEl** [comment]
Let me know if you want the vim change reverted, some other change or merely don't want to merge it when you can. Thanks for the awesome fork. I am also working on trying to get your opencmd to work with zsh but am considering how the right hand prompt might affect that. I've gotten much better at git so you don't have to fear of mistakes in any of my merges as much but am nevertheless not perfect.

**Comment by goldcoders** [comment]
i tried installing this patch, how do i use this keyboard select?
do i neeed to press escape, im using zsh , with some keybindings luke added
when i try to press jk im just scrolling inside my history
can you tell me specifically how you use this on your end?

**Comment by ZakharEl** [comment]
The patch is already applied within the keyboard select branch - no need to apply the patch again.
1. Go to https://github.com/ZakharEl/st/tree/keyboard-select.
2. Click on the branches in the top menu.
3. From there click on the keyboard select branch
4. Then click on the clone or download button and copy the url in the pop up field
5. Open up your terminal and within a directory of your choosing type git clone
6. Paste the url that you copied after git clone and then press enter
7. cd into the st directory that you have cloned.
8. The default keybinding is alt+shift+escape to enter keyboard select.
9. After having entered keyboard select use the arrow keys to go to the start of what you want to select and press s.
10. Use the arrows to expand the selection as desired, then press enter to confirm and copy to clipboard or press escape to cancel. Both buttons will have you exit keyboard select afterwards.

**Comment by ZakharEl** [comment]
Oh, and after pressing s you can press t to toggle block selection on and off.

**Comment by ZakharEl** [comment]
If you want to change the default keybinding for keyboard select it's line 229 in config.h. It's best to make you own branch and checkout into it first - make the change there.

**Comment by goldcoders** [comment]
thanks for the reply and tutorial how to use keyboard select hope luke patch this , for the moment ill use your branch thanks @ZakharEl

**Comment by goldcoders** [comment]
Ive implemented this to my current st build works like a charm hope this can be added by luke and merge...
Oh yeah you need to removed some of the code that pertains to your specific needs
maybe thats the reason this is isnt getting merge by @LukeSmithxyz

**Pull request closed without merging**
